### ISSUE TITLE
[Feature suggestion] Update install path

### ISSUE THREAD

**Issue by thdoan** [lite-xl/lite-xl-widgets#6]
To be consistent, the installation path for Widgets should be `{DATADIR}/libraries/widgets` (plural).

**Comment by jgmdev** [comment]
Not desirable since we are using `widget` as the base name for all other widgets and the installation path is also the require path for example:

```lua
local Widget = require "libraries.widget"
local Button = require "libraries.widget.button"
```
the above looks better than:
```lua
local Widget = require "libraries.widgets"
local Button = require "libraries.widgets.button"
```
Also changing it to plural form just because of matching the repo name doesn't merits having to adapt other code that depends on the library which would be broken because of no longer valid `require` path.
